services:
  - type: web
    name: moonsec-deobfuscator-bot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DOTNET_VERSION
        value: 9.0
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:3000
      - key: DISCORD_BOT_TOKEN
        sync: false
        required: true
      - key: DISCORD_CLIENT_ID
        sync: false
        required: true
    healthCheckPath: /
    autoDeploy: true
